name: Worker

on:
  push:
    branches:
      - run

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml loguru

    - name: Run the script
      run: |
        python script.py

    - name: Get the current date
      id: date
      run: |
        echo "DATE=$(TZ=Asia/Shanghai date +%Y-%m-%d)" >> $GITHUB_OUTPUT

    - name: Commit
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git checkout -b ruleset
        git rm -rf .
        git add *.srs
        git commit -m "[Update] ${{ steps.date.outputs.DATE }}"
        git push origin HEAD:ruleset --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
